version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: TestDb
      POSTGRES_USER: Test
      POSTGRES_PASSWORD: Test123
    ports:
      - "5438:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: