# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - prod-webapp-api-rg01

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy-dev:
    name: Deploy to Development Environment
    runs-on: ubuntu-latest
    needs: build
    environment: dev
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C8C85ABE1ECC499BA7B1ACBB2953B1BE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1FE5440F385E4AA1A3BC87F11083DA11 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EAB4A0382CA143F386B31FA1F3C4AB51 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "prod-webapp-api-rg01"
          slot-name: "Production"
          package: .

  deploy-test:
    name: Deploy to Test Environment
    runs-on: ubuntu-latest
    needs: [build, deploy-dev]
    environment: test
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C8C85ABE1ECC499BA7B1ACBB2953B1BE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1FE5440F385E4AA1A3BC87F11083DA11 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EAB4A0382CA143F386B31FA1F3C4AB51 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "prod-webapp-api-rg01"
          slot-name: "Production"
          package: .

  deploy-prod:
    name: Deploy to Production Environment
    runs-on: ubuntu-latest
    needs: [build, deploy-test, deploy-dev]
    environment: prod
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C8C85ABE1ECC499BA7B1ACBB2953B1BE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1FE5440F385E4AA1A3BC87F11083DA11 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EAB4A0382CA143F386B31FA1F3C4AB51 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "prod-webapp-api-rg01"
          slot-name: "Production"
          package: .
