name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - main
env:
  PROJECT_PATH: "net-example-api.csproj"
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET Core SDK 9
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.x
      - name: Semantic Release
        id: release
        uses: cycjimmy/semantic-release-action@v3
        with:
          working_directory: ./net-example-api
          extra_plugins: |
            @semantic-release/commit-analyzer
            @semantic-release/release-notes-generator
            @semantic-release/github
            @semantic-release/git
            @semantic-release/exec
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: "Pack & Publish project"
        if: ${{ steps.release.outputs.new_release_version }}
        run: |
          dotnet clean
          dotnet pack ${{ env.PROJECT_PATH }} --configuration Release --include-symbols --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
